const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  saveApiKey: (apiKey) => ipcRenderer.invoke('save-api-key', apiKey),
  getApiKey: () => ipcRenderer.invoke('get-api-key'),
  saveSettings: (payload) => ipcRenderer.invoke('save-settings', payload),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  getPublishDestinations: () => ipcRenderer.invoke('get-publish-destinations'),
  updateSettings: (payload) => ipcRenderer.invoke('update-settings', payload),
  testApiConnection: (payload) => ipcRenderer.invoke('test-api-connection', payload),
  listProviderModels: (payload) => ipcRenderer.invoke('list-provider-models', payload),
  getHistory: (payload) => ipcRenderer.invoke('get-history', payload),
  getBlog: (payload) => ipcRenderer.invoke('get-blog', payload),
  updateBlog: (payload) => ipcRenderer.invoke('update-blog', payload),
  deleteBlog: (payload) => ipcRenderer.invoke('delete-blog', payload),
  clearBlogs: () => ipcRenderer.invoke('clear-blogs'),
  generateBlog: (data) => ipcRenderer.invoke('generate-blog', data),
  exportBlog: (payload) => ipcRenderer.invoke('export-blog', payload),
  exportBulk: (payload) => ipcRenderer.invoke('export-bulk', payload),
  exportHistoryCsv: (payload) => ipcRenderer.invoke('export-history-csv', payload),
  publishBlog: (payload) => ipcRenderer.invoke('publish-blog', payload),
  testPublishDestination: (payload) => ipcRenderer.invoke('test-publish-destination', payload),
  startShopifyOAuth: (payload) => ipcRenderer.invoke('start-shopify-oauth', payload),
  listShopifyBlogs: (payload) => ipcRenderer.invoke('list-shopify-blogs', payload),
  downloadImage: (payload) => ipcRenderer.invoke('download-image', payload),
  selectLocalImageFile: () => ipcRenderer.invoke('select-local-image-file'),
  attachLocalBlogImage: (payload) => ipcRenderer.invoke('attach-local-blog-image', payload),
  uploadImageToStorage: (payload) => ipcRenderer.invoke('upload-image-storage', payload),
  testImageStorage: (payload) => ipcRenderer.invoke('test-image-storage', payload),
  generateBlogImage: (payload) => ipcRenderer.invoke('generate-blog-image', payload),
  getUserApiKey: (payload) => ipcRenderer.invoke('get-user-api-key', payload),
  saveUserApiKey: (payload) => ipcRenderer.invoke('save-user-api-key', payload),
  getUserSettings: (payload) => ipcRenderer.invoke('get-user-settings', payload),
  saveUserSettings: (payload) => ipcRenderer.invoke('save-user-settings', payload),
  getAuthState: () => ipcRenderer.invoke('get-auth-state'),
  getCurrentUser: () => ipcRenderer.invoke('get-current-user'),
  setupAdmin: (payload) => ipcRenderer.invoke('setup-admin', payload),
  login: (payload) => ipcRenderer.invoke('login', payload),
  logout: () => ipcRenderer.invoke('logout'),
  listUsers: () => ipcRenderer.invoke('list-users'),
  createUser: (payload) => ipcRenderer.invoke('create-user', payload),
  updateUserAccess: (payload) => ipcRenderer.invoke('update-user-access', payload),
  changeUserPassword: (payload) => ipcRenderer.invoke('change-user-password', payload),
  deleteUser: (payload) => ipcRenderer.invoke('delete-user', payload),
  getActivities: () => ipcRenderer.invoke('get-activities'),
  getLogs: (payload) => ipcRenderer.invoke('get-logs', payload),
  getLogsStats: (payload) => ipcRenderer.invoke('get-logs-stats', payload),
  getLogsTrend: (payload) => ipcRenderer.invoke('get-logs-trend', payload),
  clearLogs: () => ipcRenderer.invoke('clear-logs'),
  getNotifications: () => ipcRenderer.invoke('get-notifications'),
  markNotificationRead: (payload) => ipcRenderer.invoke('mark-notification-read', payload),
  clearNotifications: () => ipcRenderer.invoke('clear-notifications'),
  getApiUsage: () => ipcRenderer.invoke('get-api-usage'),
  getServerApiConfig: () => ipcRenderer.invoke('get-server-api-config'),
  saveServerApiConfig: (payload) => ipcRenderer.invoke('save-server-api-config', payload),
  testServerApiConfig: (payload) => ipcRenderer.invoke('test-server-api-config', payload),
  schedulerListJobs: (payload) => ipcRenderer.invoke('scheduler-list-jobs', payload),
  schedulerCreateJob: (payload) => ipcRenderer.invoke('scheduler-create-job', payload),
  schedulerUpdateJob: (payload) => ipcRenderer.invoke('scheduler-update-job', payload),
  schedulerDeleteJob: (payload) => ipcRenderer.invoke('scheduler-delete-job', payload),
  schedulerImportCsv: (payload) => ipcRenderer.invoke('scheduler-import-csv', payload),
  schedulerListLogs: (payload) => ipcRenderer.invoke('scheduler-list-logs', payload),
  schedulerAddLog: (payload) => ipcRenderer.invoke('scheduler-add-log', payload),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  checkAppUpdate: (payload) => ipcRenderer.invoke('check-app-update', payload),
  downloadAppUpdate: (payload) => ipcRenderer.invoke('download-app-update', payload),
  installAppUpdate: (payload) => ipcRenderer.invoke('install-app-update', payload),
  scrapeWebsite: (payload) => ipcRenderer.invoke('scrape-website', payload),
  saveProductDatabase: (payload) => ipcRenderer.invoke('save-product-database', payload),
  getProductDatabase: () => ipcRenderer.invoke('get-product-database'),
  previewLink: (payload) => ipcRenderer.invoke('preview-link', payload),
  syncRemotePosts: (payload) => ipcRenderer.invoke('sync-remote-posts', payload),
  getRemotePosts: (payload) => ipcRenderer.invoke('get-remote-posts', payload),
  getRemotePostDetail: (payload) => ipcRenderer.invoke('get-remote-post-detail', payload),
  getRemotePostLinkedImages: (payload) => ipcRenderer.invoke('get-remote-post-linked-images', payload),
  updateRemotePost: (payload) => ipcRenderer.invoke('update-remote-post', payload),
  deleteRemotePost: (payload) => ipcRenderer.invoke('delete-remote-post', payload),
  getRemotePostAnalytics: () => ipcRenderer.invoke('get-remote-post-analytics'),
  testWordpressSync: (payload) => ipcRenderer.invoke('test-wordpress-sync', payload),
  getPublishHistory: (payload) => ipcRenderer.invoke('get-publish-history', payload),
  getBlogPublishStatus: (payload) => ipcRenderer.invoke('get-blog-publish-status', payload),
  getPublishAnalytics: (payload) => ipcRenderer.invoke('get-publish-analytics', payload),
  // Analytics events & realtime
  startSession: (payload) => ipcRenderer.invoke('start-session', payload),
  heartbeatSession: (payload) => ipcRenderer.invoke('heartbeat-session', payload),
  endSession: (payload) => ipcRenderer.invoke('end-session', payload),
  logAnalyticsEvent: (payload) => ipcRenderer.invoke('log-analytics-event', payload),
  getRealtimeAnalytics: (payload) => ipcRenderer.invoke('get-realtime-analytics', payload),
  listWordpressCategories: (payload) => ipcRenderer.invoke('list-wordpress-categories', payload),
  createWordpressCategory: (payload) => ipcRenderer.invoke('create-wordpress-category', payload),
  openExternal: (payload) => ipcRenderer.invoke('open-external', payload),
  showLinkContextMenu: (payload) => ipcRenderer.invoke('show-link-context-menu', payload),
  // MongoDB Configuration (for built executables)
  saveMongoDBConfig: (payload) => ipcRenderer.invoke('save-mongodb-config', payload),
  getMongoDBConfig: () => ipcRenderer.invoke('get-mongodb-config'),
  testMongoDBConnection: (payload) => ipcRenderer.invoke('test-mongodb-connection', payload),
  onAuthExpired: (callback) => {
    const listener = () => callback();
    ipcRenderer.on('auth-expired', listener);
    return () => ipcRenderer.removeListener('auth-expired', listener);
  },
  onGenerationProgress: (callback) => {
    const listener = (event, data) => callback(data);
    ipcRenderer.on('generation-progress', listener);
    return () => ipcRenderer.removeListener('generation-progress', listener);
  },
});
